source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'slim'
gem 'bootstrap-sass'
gem 'rspec-rails'
gem 'dotenv-rails'

group :development do
  gem 'quiet_assets'
  gem 'thin'
end

